[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx prisma generate", "npx next build"]

[start]
cmd = "npx prisma db push --accept-data-loss && node .next/standalone/server.js || npx next start"
